'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Save, Loader2, Trash2, RotateCcw, ArrowLeft, BookOpen, Eye, Download, RefreshCw, BarChart3 } from 'lucide-react'
import Button from '@/components/ui/Button'
import EbookPreviewModal from '@/components/features/EbookPreviewModal'

interface EbookFormData {
  title: string
  subtitle: string
  introduction: string
  keyConcepts: string
  businessUseCases: string
  toolsAndTechniques: string
  practicalExample: string
  ebookSummary: string
  ebookKeyTakeaways: string
  reviewQuestions: string
  closingMessage: string
  isActive: boolean
}

interface Props {
  lessonId: string
  courseId: string
  lessonTitle: string
  lessonOrder: number
  lessonLevel: string
  courseName: string
  courseCategory: string
  backHref: string
  initialData: EbookFormData | null
  autoGenerated: EbookFormData
}

const FIELDS: Array<{ key: keyof Omit<EbookFormData, 'isActive'>; label: string; icon: string; rows: number }> = [
  { key: 'title', label: 'ชื่อ E-Book', icon: '📌', rows: 1 },
  { key: 'subtitle', label: 'คำบรรยาย (Subtitle)', icon: '📝', rows: 2 },
  { key: 'introduction', label: 'บทนำ (Introduction)', icon: '📖', rows: 6 },
  { key: 'keyConcepts', label: 'แนวคิดหลัก (Key Concepts)', icon: '💡', rows: 8 },
  { key: 'businessUseCases', label: 'การประยุกต์ใช้ในธุรกิจ (Business Use Cases)', icon: '🏢', rows: 8 },
  { key: 'toolsAndTechniques', label: 'เครื่องมือและเทคนิค (Tools & Techniques)', icon: '🔧', rows: 8 },
  { key: 'practicalExample', label: 'ตัวอย่างปฏิบัติ (Practical Example)', icon: '⚡', rows: 8 },
  { key: 'ebookSummary', label: 'บทสรุป (Summary)', icon: '📋', rows: 6 },
  { key: 'ebookKeyTakeaways', label: 'สิ่งที่ควรจดจำ (Key Takeaways)', icon: '🎯', rows: 6 },
  { key: 'reviewQuestions', label: 'คำถามทบทวน (Review Questions)', icon: '❓', rows: 8 },
  { key: 'closingMessage', label: 'ข้อความปิดท้าย (Closing Message)', icon: '✨', rows: 4 },
]

function countWords(text: string): number {
  if (!text) return 0
  const thaiWords = text.match(/[\u0E00-\u0E7F]+/g)?.length || 0
  const engWords = text.match(/[a-zA-Z]+/g)?.length || 0
  return thaiWords + engWords
}

export default function EbookEditorClient({
  lessonId,
  courseId,
  lessonTitle,
  lessonOrder,
  lessonLevel,
  courseName,
  courseCategory,
  backHref,
  initialData,
  autoGenerated,
}: Props) {
  const router = useRouter()
  const [form, setForm] = useState<EbookFormData>(initialData || autoGenerated)
  const [saving, setSaving] = useState(false)
  const [deleting, setDeleting] = useState(false)
  const [saved, setSaved] = useState(false)
  const [isCustom, setIsCustom] = useState(!!initialData)
  const [showPreview, setShowPreview] = useState(false)

  const allContent = [
    form.introduction, form.keyConcepts, form.businessUseCases,
    form.toolsAndTechniques, form.practicalExample, form.ebookSummary,
    form.ebookKeyTakeaways, form.reviewQuestions, form.closingMessage,
  ].join(' ')
  const totalWords = countWords(allContent)
  const estimatedPages = 2 + Math.max(1, Math.ceil(allContent.length / 800)) + 1
  const meetsMinimum = totalWords >= 2500

  const handleChange = (key: keyof EbookFormData, value: string | boolean) => {
    setForm(prev => ({ ...prev, [key]: value }))
    setSaved(false)
  }

  const handleSave = async () => {
    setSaving(true)
    try {
      const res = await fetch(`/api/admin/ebooks/${lessonId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      })
      if (res.ok) {
        setSaved(true)
        setIsCustom(true)
        setTimeout(() => setSaved(false), 3000)
      }
    } catch (err) {
      console.error(err)
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async () => {
    if (!confirm('ต้องการลบข้อมูล E-Book ที่กำหนดเองและใช้ข้อมูลอัตโนมัติแทนใช่ไหม?')) return
    setDeleting(true)
    try {
      await fetch(`/api/admin/ebooks/${lessonId}`, { method: 'DELETE' })
      setForm(autoGenerated)
      setIsCustom(false)
      setSaved(false)
    } catch (err) {
      console.error(err)
    } finally {
      setDeleting(false)
    }
  }

  const handleReset = () => {
    if (!confirm('ต้องการรีเซ็ตข้อมูลจาก Auto-Generate?')) return
    setForm(autoGenerated)
    setSaved(false)
  }

  const previewLesson = {
    id: lessonId, title: lessonTitle, subtitle: form.subtitle || null,
    lessonOrder, lessonLevel, courseName, courseCategory,
  }

  const previewEbook = {
    title: form.title, subtitle: form.subtitle || null, coverImageUrl: null,
    introduction: form.introduction || null, keyConcepts: form.keyConcepts || null,
    businessUseCases: form.businessUseCases || null, toolsAndTechniques: form.toolsAndTechniques || null,
    practicalExample: form.practicalExample || null, ebookSummary: form.ebookSummary || null,
    ebookKeyTakeaways: form.ebookKeyTakeaways || null, reviewQuestions: form.reviewQuestions || null,
    closingMessage: form.closingMessage || null, isActive: form.isActive,
  }

  const previewSettings = {
    watermarkText: 'AI SPUBUS Academy | คณะบริหารธุรกิจ ม.ศรีปทุม',
    watermarkOpacity: 0.15, headerText: 'AI SPUBUS Academy',
    footerText: 'คณะบริหารธุรกิจ มหาวิทยาลัยศรีปทุม',
    logoUrl: null, isWatermarkEnabled: true, accentColor: '#1e40af',
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <a href={backHref} className="inline-flex items-center gap-1.5 text-sm text-gray-400 transition-colors hover:text-white">
          <ArrowLeft className="h-4 w-4" /> กลับ
        </a>

        <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div className="flex items-start gap-3">
            <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500/20 to-cyan-500/20">
              <BookOpen className="h-6 w-6 text-blue-400" />
            </div>
            <div>
              <div className="flex flex-wrap items-center gap-2">
                <h1 className="text-xl font-bold text-white">Edit E-Book — บทที่ {lessonOrder}</h1>
                {isCustom ? (
                  <span className="rounded-full bg-green-500/10 px-2.5 py-0.5 text-xs font-medium text-green-400 ring-1 ring-green-500/20">Custom</span>
                ) : (
                  <span className="rounded-full bg-blue-500/10 px-2.5 py-0.5 text-xs font-medium text-blue-400 ring-1 ring-blue-500/20">Auto-Generated</span>
                )}
              </div>
              <p className="mt-0.5 text-sm text-gray-500">{lessonTitle}</p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <Button variant="ghost" size="sm" onClick={() => setShowPreview(true)} className="text-blue-400 hover:text-blue-300">
              <Eye className="h-4 w-4" /> Preview
            </Button>
            <Button variant="ghost" size="sm" onClick={handleReset} className="text-gray-400 hover:text-white">
              <RotateCcw className="h-4 w-4" /> Regenerate
            </Button>
            {isCustom && (
              <Button variant="ghost" size="sm" onClick={handleDelete} disabled={deleting} className="text-red-400 hover:text-red-300">
                {deleting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Trash2 className="h-4 w-4" />}
                ลบ Custom
              </Button>
            )}
            <Button variant="primary" size="sm" onClick={handleSave} disabled={saving}>
              {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : saved ? '✓ บันทึกแล้ว' : <><Save className="h-4 w-4" /> บันทึก</>}
            </Button>
          </div>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        <div className="rounded-xl border border-white/[0.06] bg-[#0a1628]/50 px-5 py-4">
          <div className="flex items-center gap-2 text-sm text-gray-400"><BarChart3 className="h-4 w-4" /> จำนวนคำ</div>
          <p className={`mt-1 text-2xl font-bold ${meetsMinimum ? 'text-green-400' : 'text-yellow-400'}`}>{totalWords.toLocaleString()}</p>
          <p className="mt-0.5 text-[10px] text-gray-500">{meetsMinimum ? '✓ ผ่านเกณฑ์ขั้นต่ำ (2,500 คำ)' : `ยังไม่ถึง 2,500 คำ (ขาดอีก ${(2500 - totalWords).toLocaleString()} คำ)`}</p>
        </div>
        <div className="rounded-xl border border-white/[0.06] bg-[#0a1628]/50 px-5 py-4">
          <div className="flex items-center gap-2 text-sm text-gray-400"><BookOpen className="h-4 w-4" /> จำนวนหน้า (PDF)</div>
          <p className={`mt-1 text-2xl font-bold ${estimatedPages >= 7 ? 'text-green-400' : 'text-yellow-400'}`}>~{estimatedPages}</p>
          <p className="mt-0.5 text-[10px] text-gray-500">{estimatedPages >= 7 ? '✓ ผ่านเกณฑ์ขั้นต่ำ (7 หน้า)' : 'ยังไม่ถึง 7 หน้า'}</p>
        </div>
        <div className="rounded-xl border border-white/[0.06] bg-[#0a1628]/50 px-5 py-4">
          <div className="flex items-center gap-2 text-sm text-gray-400"><RefreshCw className="h-4 w-4" /> สถานะ</div>
          <p className="mt-1 text-2xl font-bold text-white">{isCustom ? 'Custom' : 'Auto'}</p>
          <p className="mt-0.5 text-[10px] text-gray-500">{isCustom ? 'แก้ไขด้วยตนเอง' : 'สร้างอัตโนมัติจากบทเรียน'}</p>
        </div>
      </div>

      {/* Status toggle */}
      <div className="flex items-center justify-between rounded-xl border border-white/[0.06] bg-[#0a1628]/50 px-5 py-4">
        <div>
          <p className="text-sm font-medium text-gray-200">สถานะ E-Book</p>
          <p className="mt-0.5 text-xs text-gray-500">เมื่อปิด นักเรียนจะไม่เห็นปุ่มดาวน์โหลด E-Book</p>
        </div>
        <button
          onClick={() => handleChange('isActive', !form.isActive)}
          className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${form.isActive ? 'bg-blue-600' : 'bg-gray-600'}`}
        >
          <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${form.isActive ? 'translate-x-6' : 'translate-x-1'}`} />
        </button>
      </div>

      {/* Form fields */}
      <div className="space-y-5">
        {FIELDS.map(field => {
          const fieldWords = countWords(form[field.key] as string)
          return (
            <div key={field.key} className="rounded-xl border border-white/[0.06] bg-[#0a1628]/50 p-5">
              <div className="mb-2 flex items-center justify-between">
                <label className="flex items-center gap-2 text-sm font-medium text-gray-200">
                  <span>{field.icon}</span> {field.label}
                </label>
                {field.rows > 1 && <span className="text-[10px] text-gray-500">{fieldWords} คำ</span>}
              </div>
              {field.rows === 1 ? (
                <input
                  type="text"
                  value={form[field.key] as string}
                  onChange={e => handleChange(field.key, e.target.value)}
                  className="w-full rounded-lg border border-white/[0.08] bg-white/[0.04] px-4 py-2.5 text-sm text-gray-200 outline-none transition-colors placeholder:text-gray-600 focus:border-blue-500/50 focus:ring-1 focus:ring-blue-500/20"
                  placeholder={`กรอก${field.label}...`}
                />
              ) : (
                <textarea
                  value={form[field.key] as string}
                  onChange={e => handleChange(field.key, e.target.value)}
                  rows={field.rows}
                  className="w-full resize-y rounded-lg border border-white/[0.08] bg-white/[0.04] px-4 py-2.5 text-sm text-gray-200 outline-none transition-colors placeholder:text-gray-600 focus:border-blue-500/50 focus:ring-1 focus:ring-blue-500/20"
                  placeholder={`กรอก${field.label}... (ใช้ Enter เพื่อขึ้นบรรทัดใหม่)`}
                />
              )}
            </div>
          )
        })}
      </div>

      {/* Bottom */}
      <div className="flex justify-end gap-3 border-t border-white/[0.06] pt-4 pb-8">
        <Button variant="ghost" size="lg" onClick={() => setShowPreview(true)}>
          <Eye className="h-5 w-5" /> Preview PDF
        </Button>
        <Button variant="primary" size="lg" onClick={handleSave} disabled={saving}>
          {saving ? <><Loader2 className="h-5 w-5 animate-spin" /> กำลังบันทึก...</> : saved ? '✓ บันทึกเรียบร้อย' : <><Save className="h-5 w-5" /> บันทึก E-Book</>}
        </Button>
      </div>

      {/* Preview Modal */}
      {showPreview && (
        <EbookPreviewModal
          lesson={previewLesson}
          ebook={previewEbook}
          settings={previewSettings}
          onClose={() => setShowPreview(false)}
        />
      )}
    </div>
  )
}
