import { notFound } from 'next/navigation'
import db from '@/lib/db'
import { requireAdmin } from '@/lib/auth'
import { getLocale } from 'next-intl/server'
import EbookEditorClient from './EbookEditorClient'

// Auto-generate content from lesson metadata
function autoGenerateContent(lesson: {
  title: string
  subtitle: string | null
  description: string | null
  summary: string | null
  learningOutcomes: string | null
  keyTakeaways: string | null
  lessonLevel: string
  course: { title: string; category: string }
}) {
  const level =
    lesson.lessonLevel === 'BEGINNER'
      ? 'ระดับเริ่มต้น'
      : lesson.lessonLevel === 'INTERMEDIATE'
      ? 'ระดับกลาง'
      : 'ระดับขั้นสูง'

  return {
    title: lesson.title,
    subtitle: lesson.subtitle || `สรุปเนื้อหาและแนวคิดสำคัญ | ${lesson.course.category}`,
    introduction: `บทเรียนนี้เป็นส่วนหนึ่งของหลักสูตร "${lesson.course.title}" ในหัวข้อ "${lesson.title}" (${level})\n\n${lesson.description || 'เนื้อหาในบทเรียนนี้ครอบคลุมแนวคิดและทักษะที่สำคัญสำหรับการประยุกต์ใช้ในโลกธุรกิจยุคดิจิทัล'}`,
    keyConcepts:
      lesson.summary ||
      `แนวคิดหลักในบทเรียนนี้ครอบคลุมหัวข้อสำคัญที่เกี่ยวข้องกับ ${lesson.title} ซึ่งเป็นองค์ความรู้พื้นฐานในสาขา ${lesson.course.category}`,
    businessUseCases: `การประยุกต์ใช้ในธุรกิจจริง:\n- การนำแนวคิดจาก ${lesson.title} ไปปรับใช้กับองค์กรในยุคดิจิทัล\n- กรณีศึกษาจากบริษัทชั้นนำที่ประสบความสำเร็จ\n- แนวทางการวัดผลและประเมินความสำเร็จ`,
    toolsAndTechniques: `เครื่องมือและเทคนิคที่แนะนำ:\n- เทคโนโลยีและแพลตฟอร์มที่เกี่ยวข้องกับ ${lesson.course.category}\n- กรอบแนวคิดและโมเดลที่ใช้ในการวิเคราะห์\n- แหล่งข้อมูลและทรัพยากรเพิ่มเติมสำหรับการเรียนรู้`,
    practicalExample: `ตัวอย่างปฏิบัติ:\n\nสมมุติสถานการณ์: บริษัทขนาดกลางต้องการนำแนวคิดจากบทเรียน "${lesson.title}" มาปรับใช้\n\nขั้นตอนที่ 1: วิเคราะห์สถานการณ์ปัจจุบัน\nขั้นตอนที่ 2: กำหนดเป้าหมายและ KPI\nขั้นตอนที่ 3: วางแผนการดำเนินงาน\nขั้นตอนที่ 4: ติดตามและปรับปรุง`,
    ebookSummary:
      lesson.summary ||
      `บทเรียน "${lesson.title}" ได้นำเสนอแนวคิดและทักษะสำคัญในด้าน ${lesson.course.category} ซึ่งมีประโยชน์อย่างมากสำหรับการพัฒนาศักยภาพในโลกธุรกิจยุคใหม่`,
    ebookKeyTakeaways:
      lesson.keyTakeaways ||
      `- ความเข้าใจในแนวคิดหลักของ ${lesson.title}\n- ทักษะการประยุกต์ใช้ในบริบทธุรกิจจริง\n- แนวทางการพัฒนาต่อยอดอย่างต่อเนื่อง`,
    reviewQuestions: `คำถามทบทวนความเข้าใจ:\n\n1. อธิบายแนวคิดสำคัญของ "${lesson.title}" โดยสังเขป\n2. ยกตัวอย่างการประยุกต์ใช้ในธุรกิจที่คุณคุ้นเคย\n3. ความท้าทายหลักในการนำแนวคิดนี้ไปปฏิบัติคืออะไร\n4. จะวัดความสำเร็จของการนำไปใช้ได้อย่างไร\n5. แนวทางการพัฒนาทักษะนี้ต่อไปในอนาคต`,
    closingMessage: `ขอแสดงความยินดีที่คุณได้ศึกษาบทเรียนนี้จนเสร็จสมบูรณ์ การเรียนรู้อย่างต่อเนื่องคือกุญแจสำคัญสู่ความสำเร็จในยุคดิจิทัล\n\nขอให้นำความรู้ที่ได้ไปประยุกต์ใช้ให้เกิดประโยชน์สูงสุด\n\n— ทีมงาน AI Business Academy\nคณะบริหารธุรกิจ มหาวิทยาลัยศรีปทุม`,
    isActive: true,
  }
}

export default async function AdminEbookEditorPage({
  params,
}: {
  params: Promise<{ id: string; lessonId: string }>
}) {
  await requireAdmin()
  const locale = await getLocale()
  const { id: courseId, lessonId } = await params

  const lesson = await db.lesson.findUnique({
    where: { id: lessonId },
    include: {
      course: { select: { id: true, title: true, category: true } },
      ebook: true,
    },
  })

  if (!lesson || lesson.courseId !== courseId) {
    notFound()
  }

  const autoGen = autoGenerateContent(lesson)

  const initialData = lesson.ebook
    ? {
        title: lesson.ebook.title || lesson.title,
        subtitle: lesson.ebook.subtitle || '',
        introduction: lesson.ebook.introduction || '',
        keyConcepts: lesson.ebook.keyConcepts || '',
        businessUseCases: lesson.ebook.businessUseCases || '',
        toolsAndTechniques: lesson.ebook.toolsAndTechniques || '',
        practicalExample: lesson.ebook.practicalExample || '',
        ebookSummary: lesson.ebook.ebookSummary || '',
        ebookKeyTakeaways: lesson.ebook.ebookKeyTakeaways || '',
        reviewQuestions: lesson.ebook.reviewQuestions || '',
        closingMessage: lesson.ebook.closingMessage || '',
        isActive: lesson.ebook.isActive,
      }
    : null

  return (
    <EbookEditorClient
      lessonId={lessonId}
      courseId={courseId}
      lessonTitle={lesson.title}
      lessonOrder={lesson.lessonOrder}
      lessonLevel={lesson.lessonLevel}
      courseName={lesson.course.title}
      courseCategory={lesson.course.category}
      backHref={`/${locale}/admin/courses/${courseId}`}
      initialData={initialData}
      autoGenerated={autoGen}
    />
  )
}
