/**
 * Seed: 6 New Courses (Part 2 — Courses 10-12)
 * AI Entrepreneurship, AI Communication, AI Strategy
 */
import { CourseLevel, CorrectAnswer } from "@prisma/client";
import type { NewCourseSeed } from "./seed-new-courses-1";

// ═══════════════════════════════════════════════════════════════════════════════
// COURSE 10: AI for Entrepreneurship & Innovation
// ═══════════════════════════════════════════════════════════════════════════════
const aiEntrepreneur: NewCourseSeed = {
  courseCode: "AIENT-001",
  slug: "ai-entrepreneurship-innovation",
  title: "AI for Entrepreneurship & Innovation",
  shortDescription: "ใช้ AI สร้างธุรกิจใหม่และ innovate ธุรกิจเดิม",
  description: "หลักสูตรสำหรับผู้ประกอบการและนักสร้างสรรค์ที่ต้องการใช้ AI เป็นเครื่องมือในการค้นหาโอกาสทางธุรกิจ สร้าง MVP, Validate Idea และ Scale ธุรกิจอย่างรวดเร็ว",
  category: "AI Entrepreneurship",
  level: CourseLevel.INTERMEDIATE,
  duration: "5 ชั่วโมง",
  pathGroup: "APPLIED",
  pathOrder: 8,
  lessons: [
    {
      id: "lesson-ent-1", title: "AI-Powered Idea Validation",
      subtitle: "ใช้ AI ค้นหาและตรวจสอบไอเดียธุรกิจ",
      description: "เรียนรู้การใช้ AI ค้นหา market gap, validate business idea และประเมิน market size",
      youtubeUrl: "https://www.youtube.com/watch?v=SEDvD1IICfE",
      videoTitle: "ใช้ AI หาไอเดียธุรกิจและ Validate", videoChannel: "Startup AI TH", durationText: "25:00",
      lessonLevel: CourseLevel.INTERMEDIATE, lessonOrder: 1,
      summary: "AI ช่วย validate ไอเดียธุรกิจได้เร็วขึ้น ตั้งแต่ Market Research, Competitor Analysis ไปจนถึง Customer Discovery",
      learningOutcomes: "1. ใช้ AI หา Market Gap\n2. Validate ไอเดียด้วยข้อมูล\n3. ประเมิน Market Size",
      keyTakeaways: "1. AI ช่วย Market Research เร็วขึ้น 10 เท่า\n2. ใช้ ChatGPT/Claude วิเคราะห์ Competitor\n3. AI Survey Analysis เข้าใจลูกค้า\n4. TAM/SAM/SOM ด้วย AI\n5. Fail fast ด้วย data ไม่ใช่ gut feeling",
      coverImage: "/images/covers/lessons/ent-1.svg",
      inVideoQuizzes: [
        { question: "Idea Validation สำคัญอย่างไรก่อนเริ่มธุรกิจ?", optionA: "ลดความเสี่ยงของการลงทุนในไอเดียที่ตลาดไม่ต้องการ", optionB: "ไม่สำคัญ ทำเลยดีกว่า", optionC: "สำคัญแค่กับธุรกิจใหญ่", optionD: "เสียเวลาเปล่า", correctAnswer: "A", explanation: "90% ของ startup ล้มเหลวเพราะ no market need — Validation ลดความเสี่ยงนี้", triggerPercent: 25, sortOrder: 1 },
        { question: "TAM, SAM, SOM คืออะไร?", optionA: "Total Addressable Market, Serviceable Available Market, Serviceable Obtainable Market", optionB: "การจัด ranking ลูกค้า", optionC: "วิธีคำนวณกำไร", optionD: "ประเภทของ AI", correctAnswer: "A", explanation: "TAM = ตลาดทั้งหมด, SAM = ตลาดที่เข้าถึงได้, SOM = ตลาดที่จับได้จริง — ช่วยประเมินขนาดโอกาส", triggerPercent: 70, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-ent-2", title: "สร้าง MVP ด้วย AI Tools",
      subtitle: "Minimum Viable Product อย่างรวดเร็วด้วย AI",
      description: "ใช้ AI ช่วยสร้าง MVP ตั้งแต่ Design, Prototype, Landing Page ไปจนถึง Coding",
      youtubeUrl: null,
      videoTitle: "สร้าง MVP ด้วย AI ภายใน 1 สัปดาห์", videoChannel: "Builder TH", durationText: "28:00",
      lessonLevel: CourseLevel.INTERMEDIATE, lessonOrder: 2,
      summary: "AI ลดเวลาสร้าง MVP จากเดือนเหลือสัปดาห์ ด้วย AI Design, AI Coding, AI Copywriting",
      learningOutcomes: "1. สร้าง MVP ด้วย AI Tools\n2. ทำ Landing Page ด้วย AI\n3. สร้าง Prototype ได้เร็ว",
      keyTakeaways: "1. V0/Bolt.new สร้าง web app จาก prompt\n2. Cursor/Copilot ช่วยเขียนโค้ด\n3. Figma AI ออกแบบ UI\n4. ChatGPT เขียน copy และ content\n5. Ship fast, iterate faster",
      coverImage: "/images/covers/lessons/ent-2.svg",
      inVideoQuizzes: [
        { question: "MVP คืออะไร?", optionA: "ผลิตภัณฑ์ที่มี feature น้อยที่สุดที่ทดสอบ value proposition ได้", optionB: "ผลิตภัณฑ์ที่สมบูรณ์แบบ", optionC: "ผลิตภัณฑ์ที่ถูกที่สุด", optionD: "ผลิตภัณฑ์ขนาดเล็ก", correctAnswer: "A", explanation: "MVP = Minimum Viable Product สร้าง feature น้อยที่สุดที่พิสูจน์ว่าลูกค้าต้องการ", triggerPercent: 25, sortOrder: 1 },
        { question: "No-Code AI Tools ช่วย Startup อย่างไร?", optionA: "สร้าง product ได้โดยไม่ต้องมีทีม developer ลดต้นทุนและเวลา", optionB: "ทำให้ product ดีกว่า coded app", optionC: "ไม่มีข้อจำกัดเลย", optionD: "ใช้ได้เฉพาะ website", correctAnswer: "A", explanation: "No-Code AI ช่วยให้ non-technical founders สร้าง MVP ได้ด้วยตัวเอง ลดต้นทุนช่วงเริ่มต้น", triggerPercent: 70, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-ent-3", title: "AI Growth Hacking & Marketing",
      subtitle: "เร่งการเติบโตธุรกิจด้วย AI",
      description: "เทคนิค Growth Hacking ด้วย AI: Content Marketing, SEO, Social Media, Email Automation",
      youtubeUrl: null,
      videoTitle: "AI Growth Hacking สำหรับ Startup", videoChannel: "Growth TH", durationText: "24:00",
      lessonLevel: CourseLevel.INTERMEDIATE, lessonOrder: 3,
      summary: "ใช้ AI เร่ง growth: สร้าง content ด้วย AI, optimize SEO, automate email campaigns และ analyze user behavior",
      learningOutcomes: "1. ใช้ AI สร้าง Content Marketing\n2. Optimize SEO ด้วย AI\n3. Automate Growth Campaigns",
      keyTakeaways: "1. AI Content สร้าง blog/social ได้ 10x\n2. AI SEO วิเคราะห์ keyword และ optimize\n3. AI Email ส่ง personalized campaigns\n4. A/B Testing ด้วย AI\n5. วัดผล metrics ทุก channel",
      coverImage: "/images/covers/lessons/ent-3.svg",
      inVideoQuizzes: [
        { question: "Growth Hacking ต่างจาก Marketing ทั่วไปอย่างไร?", optionA: "เน้น rapid experimentation และ data-driven growth แทน traditional campaigns", optionB: "ใช้งบน้อยกว่าเสมอ", optionC: "ไม่ต้องวัดผล", optionD: "ทำเฉพาะ online", correctAnswer: "A", explanation: "Growth Hacking เน้นทดลองเร็ว วัดผลเร็ว ปรับเร็ว ใช้ data ตัดสินใจทุกขั้นตอน", triggerPercent: 30, sortOrder: 1 },
        { question: "AI ช่วย SEO อย่างไร?", optionA: "วิเคราะห์ keyword, สร้าง content ตรง search intent, ปรับปรุง ranking factors", optionB: "สร้าง backlink อัตโนมัติ", optionC: "Hack Google algorithm", optionD: "ซื้อ ranking", correctAnswer: "A", explanation: "AI วิเคราะห์ keyword opportunity, search intent, content gap แล้วช่วยสร้าง content ที่ตอบโจทย์", triggerPercent: 65, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-ent-4", title: "AI Business Model Innovation",
      subtitle: "สร้าง Business Model ใหม่ด้วย AI",
      description: "ใช้ AI เปลี่ยน Business Model จาก traditional สู่ AI-native ตั้งแต่ Revenue Model ถึง Value Proposition",
      youtubeUrl: null,
      videoTitle: "AI Business Model Innovation", videoChannel: "Innovation TH", durationText: "26:00",
      lessonLevel: CourseLevel.INTERMEDIATE, lessonOrder: 4,
      summary: "AI เปิดโอกาส Business Model ใหม่: AI-as-a-Service, Data Monetization, Freemium AI และ Platform Business",
      learningOutcomes: "1. ออกแบบ AI-Native Business Model\n2. สร้าง Value Proposition Canvas ด้วย AI\n3. วิเคราะห์ Revenue Stream ใหม่",
      keyTakeaways: "1. AI-as-a-Service โมเดลยอดนิยม\n2. Data Monetization สร้างรายได้จากข้อมูล\n3. Freemium + AI upsell ใช้ได้ดี\n4. Platform + AI สร้าง Network Effect\n5. ต้อง iterate business model อยู่เสมอ",
      coverImage: "/images/covers/lessons/ent-4.svg",
      inVideoQuizzes: [
        { question: "AI-as-a-Service (AIaaS) คืออะไร?", optionA: "ให้บริการ AI ผ่าน cloud แบบจ่ายตามการใช้งาน", optionB: "ขาย hardware AI", optionC: "จ้าง AI consultant", optionD: "สอน AI", correctAnswer: "A", explanation: "AIaaS ให้ลูกค้าใช้ AI ผ่าน API/cloud โดยไม่ต้องสร้างเอง เช่น OpenAI API, Google Vision API", triggerPercent: 30, sortOrder: 1 },
        { question: "Data Monetization มีรูปแบบอย่างไร?", optionA: "ขาย insights จากข้อมูล, สร้าง data products, ให้บริการ analytics", optionB: "ขายข้อมูลส่วนตัวลูกค้า", optionC: "เก็บข้อมูลไว้เฉยๆ", optionD: "ลบข้อมูลทิ้ง", correctAnswer: "A", explanation: "Data Monetization ที่ ethical คือสร้าง insights, data products, analytics services จากข้อมูล aggregate ไม่ใช่ขาย PII", triggerPercent: 65, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-ent-5", title: "Pitching & Fundraising ด้วย AI",
      subtitle: "ใช้ AI เตรียม Pitch Deck และหาเงินทุน",
      description: "ใช้ AI สร้าง Pitch Deck, Financial Projection, Investor Research และเตรียม Due Diligence",
      youtubeUrl: null,
      videoTitle: "Pitch Deck & Fundraising ด้วย AI", videoChannel: "Venture TH", durationText: "23:00",
      lessonLevel: CourseLevel.INTERMEDIATE, lessonOrder: 5,
      summary: "AI ช่วยเตรียม fundraising: สร้าง pitch deck, วิเคราะห์ investor fit, projection ที่น่าเชื่อถือ",
      learningOutcomes: "1. สร้าง Pitch Deck ด้วย AI\n2. ทำ Financial Projection\n3. วิเคราะห์ Investor Fit",
      keyTakeaways: "1. AI สร้าง pitch deck structure ได้\n2. Beautiful.ai / Gamma ทำ slide สวย\n3. AI ช่วย financial modeling\n4. ค้นหา investor ที่ fit ด้วย AI\n5. ฝึก pitch กับ AI ก่อน pitch จริง",
      coverImage: "/images/covers/lessons/ent-5.svg",
      inVideoQuizzes: [
        { question: "Pitch Deck ที่ดีต้องมีอะไรสำคัญ?", optionA: "Problem, Solution, Market Size, Traction, Team, Ask", optionB: "สไลด์เยอะที่สุด", optionC: "กราฟิกสวยอย่างเดียว", optionD: "รายละเอียดทางเทคนิคมาก", correctAnswer: "A", explanation: "Pitch Deck ควรสั้นกระชับ ครอบคลุม: ปัญหา, ทางแก้, ขนาดตลาด, ผลงาน, ทีม, สิ่งที่ต้องการ", triggerPercent: 30, sortOrder: 1 },
        { question: "AI ช่วยเตรียม Due Diligence อย่างไร?", optionA: "จัดเตรียมเอกสาร, ตรวจสอบข้อมูล, สรุป legal documents อัตโนมัติ", optionB: "ลงนามแทน", optionC: "หานักลงทุนให้", optionD: "โอนเงินให้", correctAnswer: "A", explanation: "AI ช่วยจัดเตรียม data room, วิเคราะห์ contracts, สรุปเอกสาร legal ได้เร็ว", triggerPercent: 70, sortOrder: 2 },
      ],
    },
  ],
  quiz: {
    title: "AI for Entrepreneurship & Innovation — Final Quiz",
    passingScore: 70,
    questions: [
      { question: "Idea Validation สำคัญเพราะ?", optionA: "90% ของ startup ล้มเหลวเพราะ no market need", optionB: "กฎหมายบังคับ", optionC: "ไม่สำคัญ", optionD: "นักลงทุนบังคับ", correctAnswer: "A", explanation: "Validation ลดความเสี่ยงของการลงทุนในสิ่งที่ตลาดไม่ต้องการ", sortOrder: 1 },
      { question: "MVP ควรมี feature กี่อย่าง?", optionA: "น้อยที่สุดที่พิสูจน์ value proposition ได้", optionB: "มากที่สุดเท่าที่ทำได้", optionC: "เท่ากับ competitor", optionD: "ไม่ต้องมี feature", correctAnswer: "A", explanation: "MVP = Minimum Viable — feature น้อยที่สุดที่ทดสอบสมมติฐานหลัก", sortOrder: 2 },
      { question: "Growth Hacking เน้นอะไร?", optionA: "Rapid experimentation + data-driven growth", optionB: "งบโฆษณาเยอะ", optionC: "Brand awareness", optionD: "PR", correctAnswer: "A", explanation: "ทดลองเร็ว วัดผลเร็ว ใช้ data ตัดสินใจ", sortOrder: 3 },
      { question: "AIaaS คืออะไร?", optionA: "AI-as-a-Service ให้บริการ AI ผ่าน cloud", optionB: "AI ฟรี", optionC: "AI Hardware", optionD: "AI School", correctAnswer: "A", explanation: "ลูกค้าใช้ AI ผ่าน API โดยไม่ต้องสร้างเอง", sortOrder: 4 },
      { question: "Pitch Deck ที่ดีควรมี?", optionA: "Problem, Solution, Market, Traction, Team, Ask", optionB: "50 slides", optionC: "แค่ financial projection", optionD: "แค่ demo", correctAnswer: "A", explanation: "กระชับ ครอบคลุมประเด็นหลัก ไม่เกิน 10-15 slides", sortOrder: 5 },
    ],
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// COURSE 11: AI Communication & Business Presentation
// ═══════════════════════════════════════════════════════════════════════════════
const aiComm: NewCourseSeed = {
  courseCode: "AICOM-001",
  slug: "ai-communication-business-presentation",
  title: "AI Communication & Business Presentation",
  shortDescription: "ใช้ AI ยกระดับการสื่อสารและนำเสนอทางธุรกิจ",
  description: "หลักสูตรที่จะเปลี่ยนวิธีการสื่อสารและนำเสนอทางธุรกิจด้วย AI ครอบคลุม AI Writing, AI Presentation, AI Translation, AI Video Creation และ AI Data Storytelling",
  category: "AI Communication",
  level: CourseLevel.INTERMEDIATE,
  duration: "5 ชั่วโมง",
  pathGroup: "ADVANCED",
  pathOrder: 11,
  lessons: [
    {
      id: "lesson-com-1", title: "AI Business Writing",
      subtitle: "เขียนเอกสารธุรกิจด้วย AI อย่างมืออาชีพ",
      description: "ใช้ AI เขียน Email, Report, Proposal, Memo และเอกสารธุรกิจคุณภาพระดับมืออาชีพ",
      youtubeUrl: "https://www.youtube.com/watch?v=RPiMBqb0pSE",
      videoTitle: "AI Business Writing สำหรับมืออาชีพ", videoChannel: "Professional Writing TH", durationText: "24:00",
      lessonLevel: CourseLevel.INTERMEDIATE, lessonOrder: 1,
      summary: "AI ช่วยเขียนเอกสารธุรกิจได้เร็วและมีคุณภาพ ตั้งแต่ email ถึง executive report",
      learningOutcomes: "1. เขียน Business Email ด้วย AI\n2. สร้าง Report/Proposal ด้วย AI\n3. ปรับ Tone & Style ตาม audience",
      keyTakeaways: "1. AI ช่วย draft ไม่ใช่ copy\n2. ปรับ tone ตาม audience\n3. ใช้ AI ตรวจ grammar + style\n4. Template + AI = consistency\n5. Human review ก่อนส่งเสมอ",
      coverImage: "/images/covers/lessons/com-1.svg",
      inVideoQuizzes: [
        { question: "AI ช่วยเขียน Business Email อย่างไร?", optionA: "Draft เนื้อหา, ปรับ tone, ตรวจ grammar, แนะนำ subject line", optionB: "ส่ง email แทนเราอัตโนมัติ", optionC: "อ่าน email ของคนอื่น", optionD: "ลบ email ที่ไม่ต้องการ", correctAnswer: "A", explanation: "AI ช่วย draft, ปรับ tone (formal/casual), ตรวจภาษา, แนะนำ subject line ที่ open rate สูง", triggerPercent: 25, sortOrder: 1 },
        { question: "ทำไมต้อง Human Review ก่อนส่งเอกสาร AI?", optionA: "AI อาจมี hallucination, tone ไม่เหมาะ, หรือข้อมูลไม่ update", optionB: "เพราะ AI เขียนไม่ดี", optionC: "กฎหมายบังคับ", optionD: "ไม่จำเป็นต้อง review", correctAnswer: "A", explanation: "AI อาจสร้างข้อมูลที่ไม่ถูกต้อง (hallucination) หรือ tone ไม่เหมาะกับบริบท ต้องตรวจสอบเสมอ", triggerPercent: 70, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-com-2", title: "AI Presentation Design",
      subtitle: "สร้าง Presentation ระดับมืออาชีพด้วย AI",
      description: "ใช้ AI สร้าง Slide Deck ที่สวยงามและมี impact ตั้งแต่โครงสร้าง เนื้อหา ไปจนถึง visual design",
      youtubeUrl: null,
      videoTitle: "AI Presentation Design มืออาชีพ", videoChannel: "Design TH", durationText: "26:00",
      lessonLevel: CourseLevel.INTERMEDIATE, lessonOrder: 2,
      summary: "AI Presentation Tools: Gamma, Beautiful.ai, Canva AI ช่วยสร้าง slide deck จาก text prompt ได้ในนาที",
      learningOutcomes: "1. สร้าง Presentation ด้วย AI\n2. ออกแบบ Visual ที่มี impact\n3. เลือก tool ที่เหมาะสม",
      keyTakeaways: "1. Gamma สร้าง deck จาก prompt\n2. Canva AI ออกแบบ visual\n3. Structure: Problem → Solution → Proof\n4. One idea per slide\n5. AI ช่วยออกแบบ ไม่ได้ช่วยคิด story",
      coverImage: "/images/covers/lessons/com-2.svg",
      inVideoQuizzes: [
        { question: "Presentation ที่มี impact ควรมีโครงสร้างอย่างไร?", optionA: "Problem → Solution → Evidence → Call to Action", optionB: "สไลด์เยอะที่สุด", optionC: "ข้อความเยอะในแต่ละสไลด์", optionD: "กราฟิกสวยอย่างเดียว", correctAnswer: "A", explanation: "Storytelling structure: ชี้ปัญหา → นำเสนอทางแก้ → พิสูจน์ด้วยหลักฐาน → เรียกร้อง action", triggerPercent: 30, sortOrder: 1 },
        { question: "AI Presentation Tools เช่น Gamma ช่วยอะไร?", optionA: "สร้าง slide deck จาก text prompt ปรับ layout และ design อัตโนมัติ", optionB: "นำเสนอแทนเรา", optionC: "ถ่ายวิดีโอ", optionD: "ส่ง email", correctAnswer: "A", explanation: "Gamma, Beautiful.ai ใช้ AI สร้าง slide จาก prompt เลือก layout, color, icon ให้อัตโนมัติ", triggerPercent: 65, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-com-3", title: "AI Data Storytelling",
      subtitle: "เล่าเรื่องจากข้อมูลด้วย AI",
      description: "เปลี่ยนข้อมูลดิบให้เป็นเรื่องราวที่น่าสนใจด้วย AI Visualization และ Narrative Generation",
      youtubeUrl: null,
      videoTitle: "Data Storytelling ด้วย AI", videoChannel: "Data Story TH", durationText: "25:00",
      lessonLevel: CourseLevel.INTERMEDIATE, lessonOrder: 3,
      summary: "Data Storytelling ด้วย AI: เปลี่ยนตัวเลขให้เป็นเรื่องราว ใช้ visualization ที่เหมาะสม และสร้าง narrative ที่น่าสนใจ",
      learningOutcomes: "1. เปลี่ยน data เป็น story\n2. เลือก visualization ที่เหมาะ\n3. สร้าง narrative จากข้อมูล",
      keyTakeaways: "1. Data + Context + Narrative = Story\n2. เลือก chart ตาม message\n3. AI สรุป insight จาก data\n4. ลด clutter เพิ่ม clarity\n5. ทุก chart ต้องมี 'so what?'",
      coverImage: "/images/covers/lessons/com-3.svg",
      inVideoQuizzes: [
        { question: "Data Storytelling ต่างจาก Data Reporting อย่างไร?", optionA: "Storytelling มี narrative และ context ที่ช่วยให้เข้าใจและตัดสินใจ", optionB: "เป็นสิ่งเดียวกัน", optionC: "Reporting ดีกว่า", optionD: "Storytelling ไม่ต้องใช้ข้อมูล", correctAnswer: "A", explanation: "Reporting แค่แสดงตัวเลข แต่ Storytelling เพิ่ม context + narrative ให้คนเข้าใจ 'why' และ 'so what'", triggerPercent: 30, sortOrder: 1 },
        { question: "หลักการเลือก Chart ที่ดีคือ?", optionA: "เลือกตาม message ที่ต้องการสื่อ ไม่ใช่ตามความสวย", optionB: "ใช้ pie chart เสมอ", optionC: "ใส่สีเยอะๆ", optionD: "ยิ่งซับซ้อนยิ่งดี", correctAnswer: "A", explanation: "เปรียบเทียบ → Bar Chart, แนวโน้ม → Line Chart, สัดส่วน → Pie Chart เลือกตาม message", triggerPercent: 70, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-com-4", title: "AI Video & Multimedia Content",
      subtitle: "สร้างวิดีโอและสื่อมัลติมีเดียด้วย AI",
      description: "ใช้ AI สร้างวิดีโอ, podcast, infographic และ multimedia content สำหรับธุรกิจ",
      youtubeUrl: null,
      videoTitle: "AI Video Creation สำหรับธุรกิจ", videoChannel: "Video AI TH", durationText: "27:00",
      lessonLevel: CourseLevel.INTERMEDIATE, lessonOrder: 4,
      summary: "AI Video Tools: HeyGen, Synthesia สร้าง presenter video, Runway สร้าง video จาก text, ElevenLabs สร้างเสียง",
      learningOutcomes: "1. สร้าง AI Video สำหรับธุรกิจ\n2. ใช้ AI Voice/Avatar\n3. ผลิต Multimedia Content",
      keyTakeaways: "1. HeyGen/Synthesia สร้าง AI Avatar\n2. Runway ML สร้าง video จาก prompt\n3. ElevenLabs สร้าง AI Voice\n4. Canva AI ทำ infographic\n5. ต้องระบุว่าเป็น AI-generated",
      coverImage: "/images/covers/lessons/com-4.svg",
      inVideoQuizzes: [
        { question: "AI Avatar Video เหมาะกับการใช้งานแบบไหน?", optionA: "Training video, product demo, multilingual content", optionB: "Live streaming", optionC: "ถ่ายทอดสดข่าว", optionD: "ทดแทนนักแสดง", correctAnswer: "A", explanation: "AI Avatar เหมาะกับ content ที่ต้องทำซ้ำ/หลายภาษา เช่น training, demo, localization", triggerPercent: 25, sortOrder: 1 },
        { question: "ข้อควรระวังในการใช้ AI Video คือ?", optionA: "ต้องระบุว่าเป็น AI-generated และไม่ใช้ทำ deepfake หลอกลวง", optionB: "ไม่มีข้อควรระวัง", optionC: "ราคาแพง", optionD: "คุณภาพต่ำ", correctAnswer: "A", explanation: "ต้อง disclose ว่าใช้ AI สร้าง และห้ามใช้ทำ content หลอกลวง (deepfake fraud)", triggerPercent: 70, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-com-5", title: "AI Translation & Cross-Cultural Communication",
      subtitle: "สื่อสารข้ามภาษาและวัฒนธรรมด้วย AI",
      description: "ใช้ AI แปลภาษา localize content และสื่อสารข้ามวัฒนธรรมอย่างมีประสิทธิภาพ",
      youtubeUrl: null,
      videoTitle: "AI Translation & Localization สำหรับธุรกิจ", videoChannel: "Global Business TH", durationText: "22:00",
      lessonLevel: CourseLevel.INTERMEDIATE, lessonOrder: 5,
      summary: "AI Translation ไม่ใช่แค่แปลคำ แต่ต้อง localize — ปรับให้เหมาะกับบริบทวัฒนธรรมท้องถิ่น",
      learningOutcomes: "1. ใช้ AI Translation อย่างมีประสิทธิภาพ\n2. Localize content สำหรับตลาดต่างๆ\n3. สื่อสารข้ามวัฒนธรรม",
      keyTakeaways: "1. DeepL/Google Translate + Human Review\n2. Localization ≠ Translation\n3. Cultural context สำคัญ\n4. AI ช่วย maintain consistency\n5. ต้อง review โดย native speaker",
      coverImage: "/images/covers/lessons/com-5.svg",
      inVideoQuizzes: [
        { question: "Localization ต่างจาก Translation อย่างไร?", optionA: "Localization ปรับเนื้อหาให้เหมาะกับวัฒนธรรมท้องถิ่น ไม่ใช่แค่แปลคำ", optionB: "เป็นสิ่งเดียวกัน", optionC: "Translation ดีกว่า", optionD: "Localization ถูกกว่า", correctAnswer: "A", explanation: "Translation แปลคำต่อคำ แต่ Localization ปรับ tone, humor, cultural reference, format ให้เหมาะกับแต่ละตลาด", triggerPercent: 30, sortOrder: 1 },
        { question: "ทำไม AI Translation ยังต้อง Human Review?", optionA: "AI อาจแปลผิดบริบท สำนวน หรือ cultural nuance", optionB: "เพราะ AI แปลไม่ได้", optionC: "กฎหมายบังคับ", optionD: "ไม่จำเป็น", correctAnswer: "A", explanation: "AI อาจแปล literal meaning ถูก แต่พลาด nuance, idiom, cultural context ที่ต้องการ human judgment", triggerPercent: 65, sortOrder: 2 },
      ],
    },
  ],
  quiz: {
    title: "AI Communication & Business Presentation — Final Quiz",
    passingScore: 70,
    questions: [
      { question: "AI Business Writing ควรใช้อย่างไร?", optionA: "AI ช่วย draft, คน review ก่อนส่ง", optionB: "ส่งตรงจาก AI", optionC: "ไม่ใช้ AI เลย", optionD: "ใช้เฉพาะภาษาอังกฤษ", correctAnswer: "A", explanation: "AI draft + Human review = คุณภาพดีที่สุด", sortOrder: 1 },
      { question: "Presentation ที่ดีควรมี?", optionA: "Problem → Solution → Evidence → CTA", optionB: "ข้อมูลมากที่สุด", optionC: "Animation เยอะ", optionD: "สีสันเยอะ", correctAnswer: "A", explanation: "Storytelling structure ช่วยให้ audience เข้าใจและจดจำ", sortOrder: 2 },
      { question: "Data Storytelling สำคัญเพราะ?", optionA: "ช่วยให้คนเข้าใจข้อมูลและตัดสินใจ", optionB: "ทำให้ข้อมูลสวย", optionC: "ซ่อนข้อมูลที่ไม่ดี", optionD: "ไม่สำคัญ", correctAnswer: "A", explanation: "Data + Story ช่วยให้ stakeholders เข้าใจ insight และ take action", sortOrder: 3 },
      { question: "AI Video ควรระบุอะไร?", optionA: "ต้องระบุว่าเป็น AI-generated content", optionB: "ไม่ต้องระบุ", optionC: "ระบุเฉพาะในบางประเทศ", optionD: "ระบุเมื่อถูกถาม", correctAnswer: "A", explanation: "Transparency — ต้อง disclose ว่าเป็น AI content เพื่อความโปร่งใส", sortOrder: 4 },
      { question: "Localization คืออะไร?", optionA: "ปรับเนื้อหาให้เหมาะกับวัฒนธรรมท้องถิ่น ไม่แค่แปลภาษา", optionB: "แปลคำต่อคำ", optionC: "ใช้ Google Translate", optionD: "เขียนใหม่ทั้งหมด", correctAnswer: "A", explanation: "Localization = Translation + Cultural Adaptation", sortOrder: 5 },
    ],
  },
};

// ═══════════════════════════════════════════════════════════════════════════════
// COURSE 12: AI Strategy & Future Business
// ═══════════════════════════════════════════════════════════════════════════════
const aiStrategy: NewCourseSeed = {
  courseCode: "AISTR-001",
  slug: "ai-strategy-future-business",
  title: "AI Strategy & Future Business",
  shortDescription: "วางกลยุทธ์ AI ระดับองค์กร เตรียมพร้อมธุรกิจแห่งอนาคต",
  description: "หลักสูตร capstone ที่รวมทุกความรู้เพื่อวางกลยุทธ์ AI ระดับองค์กร ครอบคลุม AI Strategy Frameworks, Digital Transformation Roadmap, AI Maturity Model, Future of Work และ AI Trends",
  category: "AI Strategy",
  level: CourseLevel.ADVANCED,
  duration: "6 ชั่วโมง",
  pathGroup: "ADVANCED",
  pathOrder: 12,
  lessons: [
    {
      id: "lesson-str-1", title: "AI Strategy Framework",
      subtitle: "กรอบแนวคิดการวางกลยุทธ์ AI",
      description: "เรียนรู้ framework การวางกลยุทธ์ AI ตั้งแต่ Assessment, Roadmap ไปจนถึง Implementation Plan",
      youtubeUrl: "https://www.youtube.com/watch?v=o7SRbr0bOqk",
      videoTitle: "AI Strategy Framework สำหรับองค์กร", videoChannel: "Strategy AI TH", durationText: "28:00",
      lessonLevel: CourseLevel.ADVANCED, lessonOrder: 1,
      summary: "AI Strategy Framework: Assess → Strategize → Plan → Implement → Scale — กรอบการวางกลยุทธ์ AI ที่ใช้ได้จริง",
      learningOutcomes: "1. ประเมิน AI Readiness ขององค์กร\n2. วาง AI Strategy Roadmap\n3. สร้าง Implementation Plan",
      keyTakeaways: "1. เริ่มจาก AI Maturity Assessment\n2. Align AI กับ Business Strategy\n3. Prioritize use cases by ROI\n4. Build vs Buy vs Partner\n5. Measure & iterate",
      coverImage: "/images/covers/lessons/str-1.svg",
      inVideoQuizzes: [
        { question: "AI Strategy ควรเริ่มจากอะไร?", optionA: "ประเมิน AI Maturity ขององค์กรก่อน แล้วค่อยวาง roadmap", optionB: "ซื้อ AI tool ทันที", optionC: "จ้าง Data Scientist", optionD: "Copy คู่แข่ง", correctAnswer: "A", explanation: "ต้อง assess สถานะปัจจุบันก่อน แล้วจึงวาง roadmap ที่ realistic", triggerPercent: 25, sortOrder: 1 },
        { question: "Build vs Buy vs Partner หมายถึง?", optionA: "ทางเลือกในการได้มาซึ่ง AI: สร้างเอง ซื้อ หรือ partner กับผู้เชี่ยวชาญ", optionB: "ขั้นตอนการพัฒนา AI", optionC: "ประเภทของ AI", optionD: "ระดับของ AI", correctAnswer: "A", explanation: "แต่ละทางเลือกมี trade-off: Build (control สูง/cost สูง), Buy (เร็ว/customization น้อย), Partner (expertise/dependency)", triggerPercent: 70, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-str-2", title: "Digital Transformation Roadmap",
      subtitle: "แผนเปลี่ยนผ่านสู่องค์กรดิจิทัล",
      description: "วาง Digital Transformation Roadmap ที่เป็นระบบ ตั้งแต่ Current State Assessment ถึง Future State Vision",
      youtubeUrl: null,
      videoTitle: "Digital Transformation Roadmap", videoChannel: "DX TH", durationText: "30:00",
      lessonLevel: CourseLevel.ADVANCED, lessonOrder: 2,
      summary: "Digital Transformation ไม่ใช่แค่ใช้เทคโนโลยี แต่เป็นการเปลี่ยนวิธีคิด กระบวนการ และวัฒนธรรมองค์กร",
      learningOutcomes: "1. วาง DX Roadmap\n2. จัดลำดับ initiative\n3. วัดผล DX",
      keyTakeaways: "1. DX = People + Process + Technology\n2. Vision ชัดเจน\n3. Quick wins สร้าง momentum\n4. Change management สำคัญ\n5. วัดผลด้วย KPI ชัดเจน",
      coverImage: "/images/covers/lessons/str-2.svg",
      inVideoQuizzes: [
        { question: "Digital Transformation ไม่ใช่แค่เรื่อง Technology แต่รวมถึง?", optionA: "People (คน) และ Process (กระบวนการ) ด้วย", optionB: "Hardware เท่านั้น", optionC: "Marketing", optionD: "การลดต้นทุน", correctAnswer: "A", explanation: "DX = การเปลี่ยนแปลง People + Process + Technology พร้อมกัน เทคโนโลยีอย่างเดียวไม่พอ", triggerPercent: 30, sortOrder: 1 },
        { question: "Quick Wins สำคัญใน DX อย่างไร?", optionA: "สร้างความเชื่อมั่นและ momentum ให้ทีม ก่อนทำโปรเจกต์ใหญ่", optionB: "ไม่สำคัญ ทำใหญ่เลย", optionC: "เป็นการเสียเวลา", optionD: "ใช้เฉพาะ startup", correctAnswer: "A", explanation: "Quick Wins พิสูจน์คุณค่าของ DX เร็ว สร้างความมั่นใจให้ stakeholders support โปรเจกต์ถัดไป", triggerPercent: 65, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-str-3", title: "Future of Work & AI",
      subtitle: "อนาคตการทำงานในยุค AI",
      description: "สำรวจผลกระทบของ AI ต่อตลาดแรงงาน ทักษะที่ต้องการ และวิธีเตรียมพร้อมสำหรับอนาคต",
      youtubeUrl: null,
      videoTitle: "Future of Work in AI Era", videoChannel: "Future Work TH", durationText: "25:00",
      lessonLevel: CourseLevel.ADVANCED, lessonOrder: 3,
      summary: "AI จะไม่แทนที่มนุษย์ แต่มนุษย์ที่ใช้ AI จะแทนที่มนุษย์ที่ไม่ใช้ — ทักษะที่ต้อง upskill",
      learningOutcomes: "1. เข้าใจผลกระทบของ AI ต่อแรงงาน\n2. ระบุทักษะที่ต้อง upskill\n3. วางแผนพัฒนาทีมสำหรับ AI era",
      keyTakeaways: "1. AI augment > AI replace\n2. Soft skills ยิ่งสำคัญขึ้น\n3. Continuous learning เป็น must\n4. Hybrid workforce (Human + AI)\n5. ทักษะ AI Literacy จำเป็นสำหรับทุกคน",
      coverImage: "/images/covers/lessons/str-3.svg",
      inVideoQuizzes: [
        { question: "ทักษะใดสำคัญที่สุดในยุค AI?", optionA: "Critical Thinking, Creativity, Emotional Intelligence, AI Literacy", optionB: "เฉพาะ coding", optionC: "เฉพาะ data science", optionD: "ไม่ต้อง upskill", correctAnswer: "A", explanation: "ทักษะที่ AI ทำไม่ได้: คิดวิเคราะห์, สร้างสรรค์, EQ + ทักษะใช้ AI (AI Literacy)", triggerPercent: 30, sortOrder: 1 },
        { question: "Hybrid Workforce หมายถึง?", optionA: "ทีมที่ทำงานร่วมกันระหว่างมนุษย์และ AI", optionB: "ทำงานที่บ้าน + ออฟฟิศ", optionC: "จ้าง freelancer", optionD: "ใช้ robot แทนคนทั้งหมด", correctAnswer: "A", explanation: "Hybrid Workforce = คนใช้ AI เป็นเครื่องมือ ทำงานร่วมกัน แต่ละฝ่ายทำในสิ่งที่ตนเก่ง", triggerPercent: 70, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-str-4", title: "AI Trends & Emerging Technologies",
      subtitle: "เทรนด์ AI และเทคโนโลยีใหม่ที่ต้องจับตา",
      description: "สำรวจ AI Trends ล่าสุด: AGI, Multimodal AI, AI Agents, Edge AI และ Quantum AI",
      youtubeUrl: null,
      videoTitle: "AI Trends 2025-2030", videoChannel: "Tech Trends TH", durationText: "26:00",
      lessonLevel: CourseLevel.ADVANCED, lessonOrder: 4,
      summary: "เทรนด์ AI ที่จะเปลี่ยนธุรกิจ: AI Agents ทำงานแทน, Multimodal AI เข้าใจทุกรูปแบบ, Small Language Models ใช้ได้ในทุกที่",
      learningOutcomes: "1. รู้จัก AI Trends สำคัญ\n2. ประเมินผลกระทบต่อธุรกิจ\n3. เตรียมพร้อมรับ disruption",
      keyTakeaways: "1. AI Agents ทำงาน complex tasks\n2. Multimodal AI = text + image + audio\n3. Small Language Models ใช้ local\n4. Edge AI ลด latency\n5. AI Regulation เพิ่มขึ้นทั่วโลก",
      coverImage: "/images/covers/lessons/str-4.svg",
      inVideoQuizzes: [
        { question: "AI Agents คืออะไร?", optionA: "AI ที่ทำงาน complex tasks ได้อย่างอิสระ มี tools และ memory", optionB: "Chatbot ธรรมดา", optionC: "หุ่นยนต์", optionD: "Software ปกติ", correctAnswer: "A", explanation: "AI Agents ต่างจาก chatbot ตรงที่มี agency — plan, use tools, remember, execute complex tasks", triggerPercent: 25, sortOrder: 1 },
        { question: "Multimodal AI หมายถึง?", optionA: "AI ที่เข้าใจและสร้าง content หลายรูปแบบ: text, image, audio, video", optionB: "AI หลายตัว", optionC: "AI หลายภาษา", optionD: "AI หลายบริษัท", correctAnswer: "A", explanation: "Multimodal AI ประมวลผลได้หลาย modality เช่น GPT-4o ที่เข้าใจทั้ง text, image, audio", triggerPercent: 70, sortOrder: 2 },
      ],
    },
    {
      id: "lesson-str-5", title: "สรุปบทเรียน: วางแผน AI Strategy สำหรับองค์กรของคุณ",
      subtitle: "Workshop: สร้าง AI Action Plan จริง",
      description: "รวมทุกความรู้จากทั้ง 12 คอร์ส สร้าง AI Strategy Action Plan ที่ใช้งานได้จริงสำหรับองค์กรของคุณ",
      youtubeUrl: null,
      videoTitle: "Workshop: สร้าง AI Strategy ของคุณ", videoChannel: "AI Academy TH", durationText: "35:00",
      lessonLevel: CourseLevel.ADVANCED, lessonOrder: 5,
      summary: "Workshop สรุปทุกอย่าง: สร้าง AI Action Plan จริงสำหรับองค์กร ตั้งแต่ vision, use cases, roadmap ถึง measurement",
      learningOutcomes: "1. สร้าง AI Vision Statement\n2. เขียน AI Action Plan\n3. กำหนด KPIs สำหรับ AI",
      keyTakeaways: "1. Vision → Strategy → Action Plan\n2. Prioritize by impact + feasibility\n3. กำหนด KPIs วัดผลชัด\n4. Build AI team & culture\n5. Start NOW — AI waits for no one",
      coverImage: "/images/covers/lessons/str-5.svg",
      inVideoQuizzes: [
        { question: "AI Action Plan ที่ดีต้องมีอะไร?", optionA: "Vision, Use Cases, Roadmap, Resources, KPIs, Timeline", optionB: "แค่ Budget", optionC: "แค่ Technology List", optionD: "ไม่ต้องมี Plan", correctAnswer: "A", explanation: "AI Action Plan ต้องครอบคลุม: เป้าหมาย, use cases, แผนงาน, ทรัพยากร, KPIs, timeline", triggerPercent: 25, sortOrder: 1 },
        { question: "ข้อคิดสำคัญที่สุดจากหลักสูตรทั้งหมดคือ?", optionA: "AI เป็นเครื่องมือที่เสริมพลังมนุษย์ ต้องเริ่มใช้ตอนนี้ ไม่ใช่รอ", optionB: "AI จะแทนที่มนุษย์ทั้งหมด", optionC: "AI แพงเกินไป", optionD: "AI ใช้ได้แค่บริษัทใหญ่", correctAnswer: "A", explanation: "AI augments humans — คนที่ใช้ AI จะแทนที่คนที่ไม่ใช้ เริ่มเรียนรู้และทดลองตั้งแต่วันนี้", triggerPercent: 70, sortOrder: 2 },
      ],
    },
  ],
  quiz: {
    title: "AI Strategy & Future Business — Final Quiz",
    passingScore: 70,
    questions: [
      { question: "AI Strategy ควรเริ่มจาก?", optionA: "AI Maturity Assessment", optionB: "ซื้อ AI ทันที", optionC: "จ้าง consultant", optionD: "รอคู่แข่งทำก่อน", correctAnswer: "A", explanation: "ประเมินสถานะปัจจุบันก่อน แล้วจึงวาง roadmap", sortOrder: 1 },
      { question: "Digital Transformation สำเร็จต้องมี?", optionA: "People + Process + Technology เปลี่ยนพร้อมกัน", optionB: "Technology อย่างเดียว", optionC: "งบประมาณมาก", optionD: "CEO ที่เก่ง IT", correctAnswer: "A", explanation: "DX ต้องเปลี่ยนทั้ง 3 ด้านพร้อมกัน", sortOrder: 2 },
      { question: "ทักษะสำคัญใน AI era?", optionA: "Critical Thinking + Creativity + AI Literacy", optionB: "Coding เท่านั้น", optionC: "MBA", optionD: "Excel", correctAnswer: "A", explanation: "ทักษะที่ AI ทำไม่ได้ + ทักษะใช้ AI = ชุดทักษะที่มีค่าที่สุด", sortOrder: 3 },
      { question: "AI Agents ต่างจาก Chatbot อย่างไร?", optionA: "มี agency — วางแผน ใช้เครื่องมือ จดจำ ทำงานซับซ้อนได้", optionB: "ตอบเร็วกว่า", optionC: "ถูกกว่า", optionD: "เหมือนกัน", correctAnswer: "A", explanation: "AI Agents สามารถ plan, use tools, remember context, execute multi-step tasks", sortOrder: 4 },
      { question: "สิ่งสำคัญที่สุดคือ?", optionA: "เริ่มใช้ AI ตอนนี้ ทดลอง วัดผล ปรับปรุง", optionB: "รอ AI สมบูรณ์แบบ", optionC: "ลงทุนมากๆ ตั้งแต่แรก", optionD: "จ้างทีม AI 100 คน", correctAnswer: "A", explanation: "Start now, start small, measure, scale — AI waits for no one", sortOrder: 5 },
    ],
  },
};

export const newCoursesPart2: NewCourseSeed[] = [aiEntrepreneur, aiComm, aiStrategy];
